name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - name: Get chrome path 
        id: browser-path
        run: |
          chrome --version && which chrome
          echo "chrome_path=$(which chrome)\n" >> $GITHUB_OUTPUT
      - name: Run tests
        env: 
          CHROME_PATH: ${{ steps.output.browser-path.chrome_path }}
        uses: GabrielBB/xvfb-action@v1
        with:
          run: python test.py
