name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: | 
          apt-get update && apt-get install -y \
            python3 \
            python3-pip \
            wget \
            gnupg \
            ca-certificates \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libxss1 \
            libxtst6 \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            x11-apps \
            fonts-liberation \
            libappindicator3-1 \
            libu2f-udev \
            libvulkan1 \
            libdrm2 \
            xdg-utils \
            xvfb \
            zip \
            && rm -rf /var/lib/apt/lists/*
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
            sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list' && \
            apt-get update && \
            apt-get install -y google-chrome-stable
          pip3 install --upgrade pip
          pip3 install pyvirtualdisplay
          pip3 install -r requirements.txt
          pip3 install -r server_requirements.txt
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$(google-chrome --version | awk '{print $3}')/linux64/chromedriver-linux64.zip \
            && unzip chromedriver-linux64.zip && rm -dfr chromedriver_linux64.zip \
            && sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver \
            && sudo chmod +x /usr/bin/chromedriver
      - run: which google-chrome
      - run: python test.py
